**NUMPY TUTORIAL**

In [1]:
import numpy as np

**Creating an numpy array**

In [2]:
list_py = [1,2,3,4,5]
array = np.array(list_py)
print(array)

[1 2 3 4 5]


In [3]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


**Arithmetic operation on list** 

In [4]:

l1=[20,30,40]
l2=[50,60,70]

print(l1)
print(l2)
print(l1+l2)


[20, 30, 40]
[50, 60, 70]
[20, 30, 40, 50, 60, 70]


**Arithmetic operation on numpy array**

In [5]:
a = np.array([20,30,40])
b = np.array([50,60,70])

print(a)
print(b)
print(a+b)


[20 30 40]
[50 60 70]
[ 70  90 110]


**Creating 2D array**

In [6]:
c = np.array([[20,30,40],[50,60,70]])
c

array([[20, 30, 40],
       [50, 60, 70]])

In [7]:
#Common error in creating 2D array

c = np.array([[20,30],[50,60,70]])
c

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [8]:
print(type(a))

<class 'numpy.ndarray'>


**Slicing**

In [9]:
arr = np.array([10,20,30,40,50,60,70,80])

arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [10]:
arr[2]

30

In [11]:
arr[2:5]

array([30, 40, 50])

In [12]:
arr[3:]

array([40, 50, 60, 70, 80])

In [13]:
arr[:5]

array([10, 20, 30, 40, 50])

In [14]:
arr = np.array([[10,20,30,40],[50,60,70,80]])

arr[0:2,0:2]

array([[10, 20],
       [50, 60]])

In [15]:
arr[0:2,0:3]

array([[10, 20, 30],
       [50, 60, 70]])

In [16]:
arr[0,1:3]

array([20, 30])

In [17]:
arr[1,0:2]

array([50, 60])

In [18]:
arr[0,0]

10

In [19]:
arr[1,3]

80

**Attributes of Array**

In [20]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [21]:
np.shape(arr)  # rows,columns

(2, 4)

In [22]:
np.size(arr)   #number of elements

8

In [23]:
np.ndim(arr)    #number of dimensions

2

In [24]:
arr.dtype       #datatype of array

dtype('int32')

**Functions**

In [25]:
a = [30,40,20,40,30]
arr = np.array(a)

In [26]:
arr.dtype              #datatype of array

dtype('int32')

In [27]:
    
type(arr)                     #datatype of variable       

numpy.ndarray

In [28]:
arr.astype(float)    

array([30., 40., 20., 40., 30.])

In [29]:
print(arr.astype(str))    #conversion of datatype

['30' '40' '20' '40' '30']


In [30]:
a =[30.8]
arr =np.array(a)
print(arr)
print(arr.astype(int))

[30.8]
[30]


**Mathematical Operations On Array**

In [31]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])

print(arr1 + arr2)                      #First way

print(np.add(arr1,arr2))                #Second way

[60 60 70 40 30]
[60 60 70 40 30]


In [39]:
arr_1 = np.array([[30,40],[20,10]])
arr_2 = np.array([[30,20],[10,20]])

print(arr_1 + arr_2)  #first way

print(np.add(arr_1,arr_2))  #second way


[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [40]:
arr_1 = np.array([[30,40],[20,10]])
arr_2 = np.array([[30,20],[10,20]])

print(arr_1 - arr_2)  #first way

print(np.subtract(arr_1,arr_2))  #second way


[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [41]:
arr_1 = np.array([[30,40],[20,10]])
arr_2 = np.array([[30,20],[10,20]])

print(arr_1 * arr_2)  #first way

print(np.multiply(arr_1,arr_2))  #second way


[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [42]:
arr_1 = np.array([[30,40],[20,10]])
arr_2 = np.array([[30,20],[10,20]])

print(arr_1 / arr_2)  #first way

print(np.divide(arr_1,arr_2))  #second way


[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [44]:
arr_1 = np.array([[3,4],[2,1]])
arr_2 = np.array([3])

print(arr_1 ** arr_2)  #first way

print(np.power(arr_1,arr_2))  #second way


[[27 64]
 [ 8  1]]
[[27 64]
 [ 8  1]]


In [50]:
arr_1 = np.array([9,16,4,1])

print(np.sqrt(arr_1))


[3. 4. 2. 1.]


**Concatenation**

In [53]:
#Concatenation in python
l1=[20,30,40]
l2=[5,6,7]

print(l1)
print(l2)
print(l1+l2)

[20, 30, 40]
[5, 6, 7]
[20, 30, 40, 5, 6, 7]


In [54]:
#Addition in numpy array
a = np.array([20,30,40])
b = np.array([5,6,7])

print(a)
print(b)
print(a+b)

[20 30 40]
[5 6 7]
[25 36 47]


In [56]:
#Concatenation in numpy

print(np.concatenate([a,b]))


[20 30 40  5  6  7]


In [66]:
a = np.array([[30,40],[50,10]])
b = np.array([[5,5],[3,3]])

print(np.concatenate([a,b]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [67]:
print(np.concatenate([a,b], axis = 0))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [71]:
print(np.concatenate([a,b], axis = 1))

[[30 40  5  5]
 [50 10  3  3]]


In [72]:
print(np.vstack([a,b]))       #VERTICAL CONCATENATION

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [70]:
print(np.hstack([a,b]))     #HORIZONTAL  CONCATENATION

[[30 40  5  5]
 [50 10  3  3]]


**SPLITTING OF THE ARRAY**

In [84]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,2)
print(b)

print(b[1])

[array([20, 40, 30]), array([40, 10, 20])]
[40 10 20]


In [85]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,3)
print(b)

print(b[2])

[array([20, 40]), array([30, 40]), array([10, 20])]
[10 20]


In [77]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,4)
print(b)

[array([20, 40]), array([30, 40]), array([10]), array([20])]


In [78]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,5)
print(b)


[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


In [79]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,6)
print(b)

[array([20]), array([40]), array([30]), array([40]), array([10]), array([20])]


In [87]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,2)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]])]


In [89]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,3)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int32)]


**ADDING OR REMOVING**

In [95]:
#Append
a = np.array([20,40,60,80])
print(np.append(a,90))       #Syntax - np.append(array,value)

[20 40 60 80 90]


In [92]:
a = np.array([[20,40],[60,80]])
print(np.append(a,90))

[20 40 60 80 90]


In [93]:
a = np.array([20,40,60,80])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [94]:
#Insert
a = np.array([20,40,60,80])
print(np.insert(a,1,50))      #Syntax - np.insert(array,index,value)

[20 50 40 60 80]


In [96]:
a = np.array([20,40,60,80])
print(np.insert(a,1,[50,60]))

[20 50 60 40 60 80]


In [98]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60]))

[20 50 60 40 60 80]


In [99]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60],axis = 0))

[[20 40]
 [50 60]
 [60 80]]


In [100]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50,60],axis = 1))

[[20 50 40]
 [60 60 80]]


In [102]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,1,[50],axis = 0))

[[20 40]
 [50 50]
 [60 80]]


In [104]:
a = np.array([[20,40],[60,80]])
print(np.insert(a,[1,2],[50,60],axis = 0))

[[20 40]
 [50 60]
 [60 80]
 [50 60]]


In [105]:
#DELETE

print(a)

[[20 40]
 [60 80]]


In [106]:
print(np.delete(a,1))

[20 60 80]


In [107]:
print(np.delete(a,1,axis = 0))

[[20 40]]


In [108]:
print(np.delete(a,1,axis = 1))

[[20]
 [60]]


**SORTING**

In [111]:
arr = np.array([7,8,4,12,9])

print(np.sort(arr))

[ 4  7  8  9 12]


In [112]:
arr = np.array([[7,8,4,12,9],[2,8,5,1,3]])

print(np.sort(arr))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


**SEARCH**

In [114]:
ar = np.array([3,4,1,7,8])
s = np.where(ar==4)     #syntax - np.where(array===search value)

print(s)

(array([1], dtype=int64),)


In [115]:
s = np.where(ar % 2 == 0)
print(s)

(array([1, 4], dtype=int64),)


In [120]:
ar1 = np.array([1,2,3,4,5,6])

ss = np.searchsorted(ar1,2)       #ARRAY HAS TO BE SORTED ALREADY FOR THIS FUNCTION
                                  #syntax - np.searchsorted(array,search value)
print(ss)

1


**FILTERING**

In [132]:
#Printing even numbers array
ar = np.array([20,30,40,50])

bl = [True,False,True,False]                         #First way

fa = ar[bl]

print(fa)




ar = np.array([20,30,40,50])
                                                                                                      
fa = ar[[True,False,True,False]]                          #Second way

print(fa)

[20 40]
[20 40]


In [126]:

ar = np.array([2,3,4,5])

b = ar>3

print(b)

[False False  True  True]


In [129]:
ar = np.array([2,3,4,5])

b = ar>3

fa = ar[b]            #First way
print(fa)




ar = np.array([2,3,4,5])
                                      #Second way
fa = ar[ar>3]
print(fa)


[4 5]
[4 5]


**Aggregating functions in arrays**


In [140]:
#1D ARRAY

a = np.array([20,40,60,70])

print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))              #cumulative sum
print(np.cumprod(a))             #cumulative product

190
70
20
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [144]:
#2D ARRAY

a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price , quantity)    

[100 150 199 200 250 130] [10 50 30 40 30 10]


In [149]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price , '\n' ,quantity)      #\n used for new line   

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]


In [151]:
c = np.cumprod([price,quantity],axis = 0)

print(c)

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]


In [152]:
print(c[1])

[1000 7500 5970 8000 7500 1300]


In [154]:
print(c[1].sum())

31270


**Statistical Functions**

In [162]:
baked_food = [200,300,150,130,200,280,170,188]

a = np.array(baked_food)

print(np.mean(a))
print(np.median(a))      #central value after sorting

import statistics as stats

print(stats.mode(a))    #NumPy cannot calculate mode 
print(np.std(a))         
print(np.var(a))      #square of std


202.25
194.0
200
55.68157235567257
3100.4375


In [163]:
#Positive Correlation : positive value(+1) shows proportional

tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]

relation = np.corrcoef([tobacco_consumption,deaths])
print(relation)


[[1.         0.99015454]
 [0.99015454 1.        ]]


In [166]:
#Negative Correlation : negative value(-1) shows inversly proportional

price = [100,200,300,400,500]
sales = [5,4,3,2,1]

relation = np.corrcoef(price,sales)
print(relation)

[[ 1. -1.]
 [-1.  1.]]


**Read and Save** 