# randint() function

In [2]:
import numpy as np

In [20]:
x = np.random.randint(1,100,10)          # generate 10 random numbers between 1 and 100
x
x.shape

(10,)

In [5]:
y = np.random.randint(1,100,10)           #everytime the resulting random numbers will be different using randint()
y

array([ 1, 91, 10, 63, 11, 79, 24,  3, 48, 84])

# seed() function

In [6]:
import numpy as np

**Value under seed = 2**

In [11]:
np.random.seed(2)
x1 = np.random.randint(2,50,5)         # generate 5 random numbers between 2 and 50
x1                                     # using seed function , the resulting random numbers will same 
                                       # when having same seed value

array([42, 17, 47, 10, 24])

In [12]:
np.random.seed(2)
x1 = np.random.randint(2,50,5)
x1

array([42, 17, 47, 10, 24])

In [13]:
np.random.seed(2)
x1 = np.random.randint(2,50,5)
x1

array([42, 17, 47, 10, 24])

**Value under seed = 5**

In [19]:
np.random.seed(5)
x2 = np.random.randint(2,50,5)
x2
x2.shape

(5,)

In [16]:
np.random.seed(5)
x2 = np.random.randint(2,50,5)
x2

array([37, 16, 49, 40, 18])

In [17]:
np.random.seed(5)
x2 = np.random.randint(2,50,5)
x2

array([37, 16, 49, 40, 18])

# meshgrid()

In [2]:
import numpy as np

In [3]:
x = np.linspace(-4,4,9)
y = np.linspace(-5,5,11)

In [8]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [9]:
y

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [10]:
X,Y = np.meshgrid(x,y)

In [11]:
X,Y

(array([[-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.],
        [-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.]]),
 array([[-5., -5., -5., -5., -5., -5., -5., -5., -5.],
        [-4., -4., -4., -4., -4., -4., -4., -4., -4.],
        [-3., -3., -3., -3., -3., -3., -3., -3., -3.],
        [-2., -2., -2., -2., -2., -2., -2., -2., -2.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        

# random.rand()


**It generates an array of random numbers sampled from a uniform distribution over the interval [0, 1)**

**This means each number in the array is a random float between 0 (inclusive) and 1 (exclusive).**

**It generates random numbers uniformly distributed between 0 and 1**

**
The shape of the array is specified by the arguments passed to np.random.rand()**.

**1. Generating a Single Random Number -
To generate a single random number between 0 and 1:**

In [1]:
import numpy as np

single_random_number = np.random.rand()
print(single_random_number)

0.3909188376968248


**2. Generating a 1D Array of Random Numbers-
To generate a 1D array with 5 random numbers:**

In [3]:
import numpy as np

random_array_1d = np.random.rand(5)
print(random_array_1d)

[0.59119152 0.66352722 0.62610905 0.4257638  0.36655744]


**3. Generating a 2D Array of Random Numbers-
To generate a 2D array with shape (3, 4):**

In [5]:
import numpy as np

random_array_2d = np.random.rand(3, 4)
print(random_array_2d)

[[0.56479671 0.87006654 0.94299859 0.73056413]
 [0.02655438 0.2731245  0.88992365 0.72578962]
 [0.0665637  0.02995157 0.99433199 0.12971425]]


**4. Generating Higher-Dimensional Arrays-
To generate a 3D array with shape (2, 3, 4):**

**The resulting array will have a shape of (2, 3, 4), meaning:

There are 2 matrices (or layers) stacked on top of each other.
Each matrix has 3 rows.
Each row has 4 columns.**

In [11]:
import numpy as np

random_array_3d = np.random.rand(2, 3, 4)
print(random_array_3d)

[[[0.00903047 0.12419487 0.54570184 0.51501902]
  [0.98274732 0.45445174 0.18245824 0.05139012]
  [0.27836917 0.63782943 0.73529143 0.02506433]]

 [[0.61135206 0.53912083 0.24598083 0.87219137]
  [0.48846966 0.79334163 0.90627514 0.71419067]
  [0.6410382  0.59114365 0.43807846 0.78900349]]]
